version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: p_app_postgres
    environment:
      - POSTGRES_USER=p_app_user
      - POSTGRES_PASSWORD=p_app_password
      - POSTGRES_DB=p_app_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "p_app_user", "-d", "p_app_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: p_app_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    container_name: p_app_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    user: "appuser"
    environment:
      - DATABASE_URL=postgresql://p_app_user:p_app_password@postgres/p_app_db
      - REDIS_URL=redis://redis:6379/0
      - TZ=Asia/Jakarta

  worker:
    build: .
    container_name: p_app_worker
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    user: "appuser"
    environment:
      - DATABASE_URL=postgresql://p_app_user:p_app_password@postgres/p_app_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - THE_ODDS_API_KEY=0766043d3fb5a06240d74c5f6d9ab7a9
      - TZ=Asia/Jakarta

  beat:
    build: .
    container_name: p_app_beat
    command: celery -A app.tasks beat --loglevel=info
    user: "root"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://p_app_user:p_app_password@postgres/p_app_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - THE_ODDS_API_KEY=0766043d3fb5a06240d74c5f6d9ab7a9
      - TZ=Asia/Jakarta

volumes:
  postgres_data:
  redis_data: